/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    companies: Company;
    'tenant-memberships': TenantMembership;
    projects: Project;
    'investment-highlights': InvestmentHighlight;
    catalysts: Catalyst;
    'share-structures': ShareStructure;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    companies: CompaniesSelect<false> | CompaniesSelect<true>;
    'tenant-memberships': TenantMembershipsSelect<false> | TenantMembershipsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'investment-highlights': InvestmentHighlightsSelect<false> | InvestmentHighlightsSelect<true>;
    catalysts: CatalystsSelect<false> | CatalystsSelect<true>;
    'share-structures': ShareStructuresSelect<false> | ShareStructuresSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Cross-tenant platform role. Leave empty for tenant-only users.
   */
  platformRole?: 'platform_admin' | null;
  status: 'active' | 'invited' | 'disabled';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies".
 */
export interface Company {
  id: number;
  legalName: string;
  displayName: string;
  /**
   * Stable public tenant slug. Used for local tenant resolution.
   */
  slug: string;
  status: 'active' | 'suspended' | 'provisioning';
  /**
   * Public website shows company profile only when Published.
   */
  publicationStatus: 'draft' | 'review' | 'published' | 'archived';
  templateKey: 'explorer';
  primaryCommodity?: string | null;
  jurisdiction?: string | null;
  tickerSymbol?: string | null;
  exchange?: string | null;
  websiteDomain?: string | null;
  subdomain?: string | null;
  brandColors?: {
    primary?: string | null;
    secondary?: string | null;
    accent?: string | null;
  };
  shortDescription: string;
  longDescription?: string | null;
  investmentThesis?: string | null;
  irContactName?: string | null;
  irContactEmail?: string | null;
  irContactPhone?: string | null;
  officeAddress?: string | null;
  socialLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Set automatically when a Review record is approved to Published.
   */
  reviewedBy?: (number | null) | User;
  reviewedAt?: string | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenant-memberships".
 */
export interface TenantMembership {
  id: number;
  user: number | User;
  tenant: number | Company;
  role: 'platform_admin' | 'company_admin' | 'editor' | 'viewer';
  status: 'active' | 'invited' | 'revoked';
  invitedAt?: string | null;
  acceptedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  tenant: number | Company;
  name: string;
  slug: string;
  /**
   * Public pages render Published records only.
   */
  status: 'draft' | 'review' | 'published' | 'archived';
  isFlagship?: boolean | null;
  commodity?: string | null;
  jurisdiction?: string | null;
  locationSummary?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  ownershipPercent?: number | null;
  stage?: ('early_exploration' | 'advanced_exploration' | 'resource_definition' | 'development' | 'production') | null;
  summary?: string | null;
  highlights?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Material technical claims require Review before Published.
   */
  technicalSummary?: string | null;
  /**
   * Source links for material technical claims.
   */
  sourceLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  displayOrder?: number | null;
  /**
   * Set automatically when a Review record is approved to Published.
   */
  reviewedBy?: (number | null) | User;
  reviewedAt?: string | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "investment-highlights".
 */
export interface InvestmentHighlight {
  id: number;
  tenant: number | Company;
  title: string;
  summary: string;
  displayOrder?: number | null;
  /**
   * Public pages render Published records only.
   */
  status: 'draft' | 'review' | 'published' | 'archived';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catalysts".
 */
export interface Catalyst {
  id: number;
  tenant: number | Company;
  title: string;
  expectedTiming?: string | null;
  summary?: string | null;
  displayOrder?: number | null;
  /**
   * Public pages render Published records only.
   */
  status: 'draft' | 'review' | 'published' | 'archived';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "share-structures".
 */
export interface ShareStructure {
  id: number;
  tenant: number | Company;
  asOfDate: string;
  sharesOutstanding?: number | null;
  options?: number | null;
  warrants?: number | null;
  fullyDiluted?: number | null;
  marketCapNote?: string | null;
  /**
   * Public pages render Published records only.
   */
  status: 'draft' | 'review' | 'published' | 'archived';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  tenant: number | Company;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'companies';
        value: number | Company;
      } | null)
    | ({
        relationTo: 'tenant-memberships';
        value: number | TenantMembership;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'investment-highlights';
        value: number | InvestmentHighlight;
      } | null)
    | ({
        relationTo: 'catalysts';
        value: number | Catalyst;
      } | null)
    | ({
        relationTo: 'share-structures';
        value: number | ShareStructure;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  platformRole?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies_select".
 */
export interface CompaniesSelect<T extends boolean = true> {
  legalName?: T;
  displayName?: T;
  slug?: T;
  status?: T;
  publicationStatus?: T;
  templateKey?: T;
  primaryCommodity?: T;
  jurisdiction?: T;
  tickerSymbol?: T;
  exchange?: T;
  websiteDomain?: T;
  subdomain?: T;
  brandColors?:
    | T
    | {
        primary?: T;
        secondary?: T;
        accent?: T;
      };
  shortDescription?: T;
  longDescription?: T;
  investmentThesis?: T;
  irContactName?: T;
  irContactEmail?: T;
  irContactPhone?: T;
  officeAddress?: T;
  socialLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  reviewedBy?: T;
  reviewedAt?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenant-memberships_select".
 */
export interface TenantMembershipsSelect<T extends boolean = true> {
  user?: T;
  tenant?: T;
  role?: T;
  status?: T;
  invitedAt?: T;
  acceptedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  slug?: T;
  status?: T;
  isFlagship?: T;
  commodity?: T;
  jurisdiction?: T;
  locationSummary?: T;
  latitude?: T;
  longitude?: T;
  ownershipPercent?: T;
  stage?: T;
  summary?: T;
  highlights?:
    | T
    | {
        item?: T;
        id?: T;
      };
  technicalSummary?: T;
  sourceLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  displayOrder?: T;
  reviewedBy?: T;
  reviewedAt?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "investment-highlights_select".
 */
export interface InvestmentHighlightsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  summary?: T;
  displayOrder?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catalysts_select".
 */
export interface CatalystsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  expectedTiming?: T;
  summary?: T;
  displayOrder?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "share-structures_select".
 */
export interface ShareStructuresSelect<T extends boolean = true> {
  tenant?: T;
  asOfDate?: T;
  sharesOutstanding?: T;
  options?: T;
  warrants?: T;
  fullyDiluted?: T;
  marketCapNote?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  tenant?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}