/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    companies: Company;
    'company-listings': CompanyListing;
    'tenant-memberships': TenantMembership;
    projects: Project;
    'investment-highlights': InvestmentHighlight;
    catalysts: Catalyst;
    'news-releases': NewsRelease;
    documents: Document;
    people: Person;
    'share-structures': ShareStructure;
    'exploration-contents': ExplorationContent;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    companies: CompaniesSelect<false> | CompaniesSelect<true>;
    'company-listings': CompanyListingsSelect<false> | CompanyListingsSelect<true>;
    'tenant-memberships': TenantMembershipsSelect<false> | TenantMembershipsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'investment-highlights': InvestmentHighlightsSelect<false> | InvestmentHighlightsSelect<true>;
    catalysts: CatalystsSelect<false> | CatalystsSelect<true>;
    'news-releases': NewsReleasesSelect<false> | NewsReleasesSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    people: PeopleSelect<false> | PeopleSelect<true>;
    'share-structures': ShareStructuresSelect<false> | ShareStructuresSelect<true>;
    'exploration-contents': ExplorationContentsSelect<false> | ExplorationContentsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Cross-tenant platform role. Leave empty for tenant-only users.
   */
  platformRole?: 'platform_admin' | null;
  status: 'active' | 'invited' | 'disabled';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies".
 */
export interface Company {
  id: number;
  legalName: string;
  displayName: string;
  /**
   * Stable public tenant slug. Used for local tenant resolution.
   */
  slug: string;
  status: 'active' | 'suspended' | 'provisioning';
  /**
   * Public website shows company profile only when Published.
   */
  publicationStatus: 'draft' | 'review' | 'published' | 'archived';
  templateKey: 'explorer' | 'summit';
  primaryCommodity?: string | null;
  jurisdiction?: string | null;
  tickerSymbol?: string | null;
  exchange?: string | null;
  websiteDomain?: string | null;
  /**
   * Exact tenant label for <subdomain>.nrlaunch.com. Platform Admin only.
   */
  subdomain?: string | null;
  brandColors?: {
    primary?: string | null;
    secondary?: string | null;
    accent?: string | null;
  };
  shortDescription: string;
  longDescription?: string | null;
  investmentThesis?: string | null;
  irContactName?: string | null;
  irContactEmail?: string | null;
  irContactPhone?: string | null;
  officeAddress?: string | null;
  socialLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Set automatically when a Review record is approved to Published.
   */
  reviewedBy?: (number | null) | User;
  reviewedAt?: string | null;
  publishedAt?: string | null;
  /**
   * Server-controlled. Company Admins cannot change origin. Defaults to human_authored.
   */
  contentOrigin?: ('human_authored' | 'machine_assisted') | null;
  originLockedAt?: string | null;
  /**
   * Page/section/region locator for machine-assisted claims (not public).
   */
  sourceLocation?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Claim-to-source references for reviewers (not public).
   */
  provenanceClaims?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  extractionRunId?: string | null;
  extractionProvider?: string | null;
  extractionModel?: string | null;
  extractionModelVersion?: string | null;
  extractedAt?: string | null;
  /**
   * Set when a reviewer acknowledges source context on approval.
   */
  reviewerSourceCheckBy?: (number | null) | User;
  reviewerSourceCheckAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company-listings".
 */
export interface CompanyListing {
  id: number;
  tenant: number | Company;
  symbol: string;
  exchange: string;
  market?: string | null;
  listingType?: ('equity' | 'otc' | 'other') | null;
  quoteCurrency?: string | null;
  isPrimary?: boolean | null;
  displayOrder?: number | null;
  /**
   * Public pages render Published records only.
   */
  status: 'draft' | 'review' | 'published' | 'archived';
  disclosureLevel: 'none' | 'standard' | 'technical';
  /**
   * http(s) source for material claims when no source document is linked.
   */
  sourceUrl?: string | null;
  /**
   * Optional tenant document used as the source reference.
   */
  sourceDocument?: (number | null) | Document;
  /**
   * Set automatically when a Review record is approved to Published.
   */
  reviewedBy?: (number | null) | User;
  reviewedAt?: string | null;
  publishedAt?: string | null;
  /**
   * Server-controlled. Company Admins cannot change origin. Defaults to human_authored.
   */
  contentOrigin?: ('human_authored' | 'machine_assisted') | null;
  originLockedAt?: string | null;
  /**
   * Page/section/region locator for machine-assisted claims (not public).
   */
  sourceLocation?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Claim-to-source references for reviewers (not public).
   */
  provenanceClaims?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  extractionRunId?: string | null;
  extractionProvider?: string | null;
  extractionModel?: string | null;
  extractionModelVersion?: string | null;
  extractedAt?: string | null;
  /**
   * Set when a reviewer acknowledges source context on approval.
   */
  reviewerSourceCheckBy?: (number | null) | User;
  reviewerSourceCheckAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  tenant: number | Company;
  title: string;
  slug: string;
  category: 'presentation' | 'technical_report' | 'financial' | 'other';
  publicationDate: string;
  /**
   * External presentation or document URL.
   */
  externalUrl?: string | null;
  file?: (number | null) | Media;
  project?: (number | null) | Project;
  /**
   * http(s) source for material claims when no source document is linked.
   */
  sourceUrl?: string | null;
  /**
   * Optional tenant document used as the source reference.
   */
  sourceDocument?: (number | null) | Document;
  disclosureLevel: 'none' | 'standard' | 'technical';
  /**
   * Public pages render Published records only.
   */
  status: 'draft' | 'review' | 'published' | 'archived';
  /**
   * Set automatically when a Review record is approved to Published.
   */
  reviewedBy?: (number | null) | User;
  reviewedAt?: string | null;
  publishedAt?: string | null;
  /**
   * Server-controlled. Company Admins cannot change origin. Defaults to human_authored.
   */
  contentOrigin?: ('human_authored' | 'machine_assisted') | null;
  originLockedAt?: string | null;
  /**
   * Page/section/region locator for machine-assisted claims (not public).
   */
  sourceLocation?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Claim-to-source references for reviewers (not public).
   */
  provenanceClaims?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  extractionRunId?: string | null;
  extractionProvider?: string | null;
  extractionModel?: string | null;
  extractionModelVersion?: string | null;
  extractedAt?: string | null;
  /**
   * Set when a reviewer acknowledges source context on approval.
   */
  reviewerSourceCheckBy?: (number | null) | User;
  reviewerSourceCheckAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  tenant: number | Company;
  alt: string;
  /**
   * Original upload name retained for display; stored object key is UUID-prefixed.
   */
  originalFilename?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  tenant: number | Company;
  name: string;
  slug: string;
  /**
   * Public pages render Published records only.
   */
  status: 'draft' | 'review' | 'published' | 'archived';
  isFlagship?: boolean | null;
  commodity?: string | null;
  jurisdiction?: string | null;
  locationSummary?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  ownershipPercent?: number | null;
  stage?: ('early_exploration' | 'advanced_exploration' | 'resource_definition' | 'development' | 'production') | null;
  summary?: string | null;
  highlights?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Material technical claims require Review before Published.
   */
  technicalSummary?: string | null;
  /**
   * Source links for material technical claims.
   */
  sourceLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  displayOrder?: number | null;
  /**
   * Set automatically when a Review record is approved to Published.
   */
  reviewedBy?: (number | null) | User;
  reviewedAt?: string | null;
  publishedAt?: string | null;
  /**
   * Server-controlled. Company Admins cannot change origin. Defaults to human_authored.
   */
  contentOrigin?: ('human_authored' | 'machine_assisted') | null;
  originLockedAt?: string | null;
  /**
   * Page/section/region locator for machine-assisted claims (not public).
   */
  sourceLocation?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Claim-to-source references for reviewers (not public).
   */
  provenanceClaims?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  extractionRunId?: string | null;
  extractionProvider?: string | null;
  extractionModel?: string | null;
  extractionModelVersion?: string | null;
  extractedAt?: string | null;
  /**
   * Set when a reviewer acknowledges source context on approval.
   */
  reviewerSourceCheckBy?: (number | null) | User;
  reviewerSourceCheckAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenant-memberships".
 */
export interface TenantMembership {
  id: number;
  user: number | User;
  tenant: number | Company;
  role: 'platform_admin' | 'company_admin' | 'editor' | 'viewer';
  status: 'active' | 'invited' | 'revoked';
  invitedAt?: string | null;
  acceptedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "investment-highlights".
 */
export interface InvestmentHighlight {
  id: number;
  tenant: number | Company;
  title: string;
  summary: string;
  displayOrder?: number | null;
  /**
   * Public pages render Published records only.
   */
  status: 'draft' | 'review' | 'published' | 'archived';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catalysts".
 */
export interface Catalyst {
  id: number;
  tenant: number | Company;
  title: string;
  expectedTiming?: string | null;
  summary?: string | null;
  displayOrder?: number | null;
  /**
   * Public pages render Published records only.
   */
  status: 'draft' | 'review' | 'published' | 'archived';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-releases".
 */
export interface NewsRelease {
  id: number;
  tenant: number | Company;
  title: string;
  slug: string;
  project?: (number | null) | Project;
  releaseDate: string;
  excerpt: string;
  body: string;
  /**
   * http(s) source for material claims when no source document is linked.
   */
  sourceUrl?: string | null;
  /**
   * Optional tenant document used as the source reference.
   */
  sourceDocument?: (number | null) | Document;
  disclosureLevel: 'none' | 'standard' | 'technical';
  /**
   * Public pages render Published records only.
   */
  status: 'draft' | 'review' | 'published' | 'archived';
  /**
   * Set automatically when a Review record is approved to Published.
   */
  reviewedBy?: (number | null) | User;
  reviewedAt?: string | null;
  publishedAt?: string | null;
  /**
   * Server-controlled. Company Admins cannot change origin. Defaults to human_authored.
   */
  contentOrigin?: ('human_authored' | 'machine_assisted') | null;
  originLockedAt?: string | null;
  /**
   * Page/section/region locator for machine-assisted claims (not public).
   */
  sourceLocation?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Claim-to-source references for reviewers (not public).
   */
  provenanceClaims?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  extractionRunId?: string | null;
  extractionProvider?: string | null;
  extractionModel?: string | null;
  extractionModelVersion?: string | null;
  extractedAt?: string | null;
  /**
   * Set when a reviewer acknowledges source context on approval.
   */
  reviewerSourceCheckBy?: (number | null) | User;
  reviewerSourceCheckAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people".
 */
export interface Person {
  id: number;
  tenant: number | Company;
  name: string;
  roleTitle: string;
  group: 'management' | 'board' | 'advisors' | 'other';
  /**
   * Biography is disclosure-sensitive and review-gated when Published.
   */
  biography: string;
  headshot?: (number | null) | Media;
  displayOrder?: number | null;
  disclosureLevel: 'none' | 'standard' | 'technical';
  /**
   * Public pages render Published records only.
   */
  status: 'draft' | 'review' | 'published' | 'archived';
  /**
   * Set automatically when a Review record is approved to Published.
   */
  reviewedBy?: (number | null) | User;
  reviewedAt?: string | null;
  publishedAt?: string | null;
  /**
   * Server-controlled. Company Admins cannot change origin. Defaults to human_authored.
   */
  contentOrigin?: ('human_authored' | 'machine_assisted') | null;
  originLockedAt?: string | null;
  /**
   * Page/section/region locator for machine-assisted claims (not public).
   */
  sourceLocation?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Claim-to-source references for reviewers (not public).
   */
  provenanceClaims?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  extractionRunId?: string | null;
  extractionProvider?: string | null;
  extractionModel?: string | null;
  extractionModelVersion?: string | null;
  extractedAt?: string | null;
  /**
   * Set when a reviewer acknowledges source context on approval.
   */
  reviewerSourceCheckBy?: (number | null) | User;
  reviewerSourceCheckAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "share-structures".
 */
export interface ShareStructure {
  id: number;
  tenant: number | Company;
  asOfDate: string;
  sharesOutstanding?: number | null;
  options?: number | null;
  warrants?: number | null;
  fullyDiluted?: number | null;
  marketCapNote?: string | null;
  /**
   * http(s) source for material claims when no source document is linked.
   */
  sourceUrl?: string | null;
  /**
   * Optional tenant document used as the source reference.
   */
  sourceDocument?: (number | null) | Document;
  /**
   * Public pages render Published records only.
   */
  status: 'draft' | 'review' | 'published' | 'archived';
  /**
   * Set automatically when a Review record is approved to Published.
   */
  reviewedBy?: (number | null) | User;
  reviewedAt?: string | null;
  publishedAt?: string | null;
  /**
   * Server-controlled. Company Admins cannot change origin. Defaults to human_authored.
   */
  contentOrigin?: ('human_authored' | 'machine_assisted') | null;
  originLockedAt?: string | null;
  /**
   * Page/section/region locator for machine-assisted claims (not public).
   */
  sourceLocation?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Claim-to-source references for reviewers (not public).
   */
  provenanceClaims?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  extractionRunId?: string | null;
  extractionProvider?: string | null;
  extractionModel?: string | null;
  extractionModelVersion?: string | null;
  extractedAt?: string | null;
  /**
   * Set when a reviewer acknowledges source context on approval.
   */
  reviewerSourceCheckBy?: (number | null) | User;
  reviewerSourceCheckAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exploration-contents".
 */
export interface ExplorationContent {
  id: number;
  tenant: number | Company;
  project: number | Project;
  title: string;
  contentDate: string;
  summary: string;
  /**
   * Material technical claims require a source reference and Review before Published.
   */
  technicalDetails: string;
  /**
   * http(s) source for material claims when no source document is linked.
   */
  sourceUrl?: string | null;
  /**
   * Optional tenant document used as the source reference.
   */
  sourceDocument?: (number | null) | Document;
  disclosureLevel: 'none' | 'standard' | 'technical';
  /**
   * Public pages render Published records only.
   */
  status: 'draft' | 'review' | 'published' | 'archived';
  /**
   * Set automatically when a Review record is approved to Published.
   */
  reviewedBy?: (number | null) | User;
  reviewedAt?: string | null;
  publishedAt?: string | null;
  /**
   * Server-controlled. Company Admins cannot change origin. Defaults to human_authored.
   */
  contentOrigin?: ('human_authored' | 'machine_assisted') | null;
  originLockedAt?: string | null;
  /**
   * Page/section/region locator for machine-assisted claims (not public).
   */
  sourceLocation?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Claim-to-source references for reviewers (not public).
   */
  provenanceClaims?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  extractionRunId?: string | null;
  extractionProvider?: string | null;
  extractionModel?: string | null;
  extractionModelVersion?: string | null;
  extractedAt?: string | null;
  /**
   * Set when a reviewer acknowledges source context on approval.
   */
  reviewerSourceCheckBy?: (number | null) | User;
  reviewerSourceCheckAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'companies';
        value: number | Company;
      } | null)
    | ({
        relationTo: 'company-listings';
        value: number | CompanyListing;
      } | null)
    | ({
        relationTo: 'tenant-memberships';
        value: number | TenantMembership;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'investment-highlights';
        value: number | InvestmentHighlight;
      } | null)
    | ({
        relationTo: 'catalysts';
        value: number | Catalyst;
      } | null)
    | ({
        relationTo: 'news-releases';
        value: number | NewsRelease;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'people';
        value: number | Person;
      } | null)
    | ({
        relationTo: 'share-structures';
        value: number | ShareStructure;
      } | null)
    | ({
        relationTo: 'exploration-contents';
        value: number | ExplorationContent;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  platformRole?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies_select".
 */
export interface CompaniesSelect<T extends boolean = true> {
  legalName?: T;
  displayName?: T;
  slug?: T;
  status?: T;
  publicationStatus?: T;
  templateKey?: T;
  primaryCommodity?: T;
  jurisdiction?: T;
  tickerSymbol?: T;
  exchange?: T;
  websiteDomain?: T;
  subdomain?: T;
  brandColors?:
    | T
    | {
        primary?: T;
        secondary?: T;
        accent?: T;
      };
  shortDescription?: T;
  longDescription?: T;
  investmentThesis?: T;
  irContactName?: T;
  irContactEmail?: T;
  irContactPhone?: T;
  officeAddress?: T;
  socialLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  reviewedBy?: T;
  reviewedAt?: T;
  publishedAt?: T;
  contentOrigin?: T;
  originLockedAt?: T;
  sourceLocation?: T;
  provenanceClaims?: T;
  extractionRunId?: T;
  extractionProvider?: T;
  extractionModel?: T;
  extractionModelVersion?: T;
  extractedAt?: T;
  reviewerSourceCheckBy?: T;
  reviewerSourceCheckAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company-listings_select".
 */
export interface CompanyListingsSelect<T extends boolean = true> {
  tenant?: T;
  symbol?: T;
  exchange?: T;
  market?: T;
  listingType?: T;
  quoteCurrency?: T;
  isPrimary?: T;
  displayOrder?: T;
  status?: T;
  disclosureLevel?: T;
  sourceUrl?: T;
  sourceDocument?: T;
  reviewedBy?: T;
  reviewedAt?: T;
  publishedAt?: T;
  contentOrigin?: T;
  originLockedAt?: T;
  sourceLocation?: T;
  provenanceClaims?: T;
  extractionRunId?: T;
  extractionProvider?: T;
  extractionModel?: T;
  extractionModelVersion?: T;
  extractedAt?: T;
  reviewerSourceCheckBy?: T;
  reviewerSourceCheckAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenant-memberships_select".
 */
export interface TenantMembershipsSelect<T extends boolean = true> {
  user?: T;
  tenant?: T;
  role?: T;
  status?: T;
  invitedAt?: T;
  acceptedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  slug?: T;
  status?: T;
  isFlagship?: T;
  commodity?: T;
  jurisdiction?: T;
  locationSummary?: T;
  latitude?: T;
  longitude?: T;
  ownershipPercent?: T;
  stage?: T;
  summary?: T;
  highlights?:
    | T
    | {
        item?: T;
        id?: T;
      };
  technicalSummary?: T;
  sourceLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  displayOrder?: T;
  reviewedBy?: T;
  reviewedAt?: T;
  publishedAt?: T;
  contentOrigin?: T;
  originLockedAt?: T;
  sourceLocation?: T;
  provenanceClaims?: T;
  extractionRunId?: T;
  extractionProvider?: T;
  extractionModel?: T;
  extractionModelVersion?: T;
  extractedAt?: T;
  reviewerSourceCheckBy?: T;
  reviewerSourceCheckAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "investment-highlights_select".
 */
export interface InvestmentHighlightsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  summary?: T;
  displayOrder?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catalysts_select".
 */
export interface CatalystsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  expectedTiming?: T;
  summary?: T;
  displayOrder?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-releases_select".
 */
export interface NewsReleasesSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  project?: T;
  releaseDate?: T;
  excerpt?: T;
  body?: T;
  sourceUrl?: T;
  sourceDocument?: T;
  disclosureLevel?: T;
  status?: T;
  reviewedBy?: T;
  reviewedAt?: T;
  publishedAt?: T;
  contentOrigin?: T;
  originLockedAt?: T;
  sourceLocation?: T;
  provenanceClaims?: T;
  extractionRunId?: T;
  extractionProvider?: T;
  extractionModel?: T;
  extractionModelVersion?: T;
  extractedAt?: T;
  reviewerSourceCheckBy?: T;
  reviewerSourceCheckAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  category?: T;
  publicationDate?: T;
  externalUrl?: T;
  file?: T;
  project?: T;
  sourceUrl?: T;
  sourceDocument?: T;
  disclosureLevel?: T;
  status?: T;
  reviewedBy?: T;
  reviewedAt?: T;
  publishedAt?: T;
  contentOrigin?: T;
  originLockedAt?: T;
  sourceLocation?: T;
  provenanceClaims?: T;
  extractionRunId?: T;
  extractionProvider?: T;
  extractionModel?: T;
  extractionModelVersion?: T;
  extractedAt?: T;
  reviewerSourceCheckBy?: T;
  reviewerSourceCheckAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people_select".
 */
export interface PeopleSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  roleTitle?: T;
  group?: T;
  biography?: T;
  headshot?: T;
  displayOrder?: T;
  disclosureLevel?: T;
  status?: T;
  reviewedBy?: T;
  reviewedAt?: T;
  publishedAt?: T;
  contentOrigin?: T;
  originLockedAt?: T;
  sourceLocation?: T;
  provenanceClaims?: T;
  extractionRunId?: T;
  extractionProvider?: T;
  extractionModel?: T;
  extractionModelVersion?: T;
  extractedAt?: T;
  reviewerSourceCheckBy?: T;
  reviewerSourceCheckAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "share-structures_select".
 */
export interface ShareStructuresSelect<T extends boolean = true> {
  tenant?: T;
  asOfDate?: T;
  sharesOutstanding?: T;
  options?: T;
  warrants?: T;
  fullyDiluted?: T;
  marketCapNote?: T;
  sourceUrl?: T;
  sourceDocument?: T;
  status?: T;
  reviewedBy?: T;
  reviewedAt?: T;
  publishedAt?: T;
  contentOrigin?: T;
  originLockedAt?: T;
  sourceLocation?: T;
  provenanceClaims?: T;
  extractionRunId?: T;
  extractionProvider?: T;
  extractionModel?: T;
  extractionModelVersion?: T;
  extractedAt?: T;
  reviewerSourceCheckBy?: T;
  reviewerSourceCheckAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exploration-contents_select".
 */
export interface ExplorationContentsSelect<T extends boolean = true> {
  tenant?: T;
  project?: T;
  title?: T;
  contentDate?: T;
  summary?: T;
  technicalDetails?: T;
  sourceUrl?: T;
  sourceDocument?: T;
  disclosureLevel?: T;
  status?: T;
  reviewedBy?: T;
  reviewedAt?: T;
  publishedAt?: T;
  contentOrigin?: T;
  originLockedAt?: T;
  sourceLocation?: T;
  provenanceClaims?: T;
  extractionRunId?: T;
  extractionProvider?: T;
  extractionModel?: T;
  extractionModelVersion?: T;
  extractedAt?: T;
  reviewerSourceCheckBy?: T;
  reviewerSourceCheckAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  tenant?: T;
  alt?: T;
  originalFilename?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}